"""Catalog metadata for the PA#0 demo console.

The catalog describes existing API demos for the frontend. It intentionally
contains no cryptographic logic; endpoint handlers remain the source of truth
for computation.
"""

HEX16 = "00112233445566778899aabbccddeeff"


DEMO_CATALOG = [
    {
        "id": "pa1-owp",
        "pa": 1,
        "title": "DLP One-Way Permutation",
        "category": "Minicrypt",
        "primitive": "OWP",
        "path": "/api/pa1/owp",
        "method": "POST",
        "default_payload": {"bits": 80, "x": 3},
        "controls": [
            {"name": "bits", "type": "number", "label": "DLP bits", "min": 32, "max": 256},
            {"name": "x", "type": "number", "label": "Input x", "min": 0},
        ],
        "result_fields": ["input", "output", "p", "q"],
        "tags": ["construction", "reduction"],
        "summary": "Evaluates g^x mod p on the DLP subgroup.",
        "claim": "DLP gives a concrete one-way permutation foundation.",
    },
    {
        "id": "pa1-prg",
        "pa": 1,
        "title": "HILL PRG",
        "category": "Minicrypt",
        "primitive": "PRG",
        "path": "/api/pa1/prg",
        "method": "POST",
        "default_payload": {"foundation": "DLP", "seed": HEX16, "output_bytes": 32, "bits": 80},
        "controls": [
            {"name": "foundation", "type": "select", "label": "Foundation", "options": ["AES", "DLP"]},
            {"name": "seed", "type": "hex", "label": "Seed"},
            {"name": "output_bytes", "type": "number", "label": "Output bytes", "min": 8, "max": 128},
        ],
        "result_fields": ["output_hex", "tests"],
        "tags": ["construction", "reduction"],
        "summary": "Expands a short seed with the hard-core-bit construction.",
        "claim": "Pseudorandomness reduces to the underlying OWF/OWP hardness.",
    },
    {
        "id": "pa2-ggm",
        "pa": 2,
        "title": "GGM Tree PRF",
        "category": "Minicrypt",
        "primitive": "PRF",
        "path": "/api/pa2/ggm",
        "method": "POST",
        "default_payload": {"key": HEX16, "x": 3, "input_bits": 4},
        "controls": [
            {"name": "key", "type": "hex", "label": "Key"},
            {"name": "x", "type": "number", "label": "Input x", "min": 0},
            {"name": "input_bits", "type": "number", "label": "Input bits", "min": 1, "max": 8},
        ],
        "result_fields": ["output_hex"],
        "tags": ["construction", "reduction"],
        "summary": "Walks a binary PRG tree to evaluate F_k(x).",
        "claim": "A secure length-doubling PRG yields a secure PRF.",
    },
    {
        "id": "pa3-cpa",
        "pa": 3,
        "title": "CPA Encryption",
        "category": "Minicrypt",
        "primitive": "CPA-Enc",
        "path": "/api/pa3/cpa",
        "method": "POST",
        "default_payload": {"key": HEX16, "message": "hello world"},
        "controls": [
            {"name": "key", "type": "hex", "label": "Key"},
            {"name": "message", "type": "text", "label": "Message"},
        ],
        "result_fields": ["r_hex", "c_hex", "recovered"],
        "tags": ["construction", "hardening"],
        "summary": "Encrypts with a fresh nonce and PRF pad.",
        "claim": "CPA security follows from PRF indistinguishability and fresh randomness.",
    },
    {
        "id": "pa4-modes",
        "pa": 4,
        "title": "Block Cipher Modes",
        "category": "Minicrypt",
        "primitive": "PRP",
        "path": "/api/pa4/modes",
        "method": "POST",
        "default_payload": {"mode": "CTR", "key": HEX16, "message": "Hello, world!"},
        "controls": [
            {"name": "mode", "type": "select", "label": "Mode", "options": ["CBC", "OFB", "CTR"]},
            {"name": "key", "type": "hex", "label": "Key"},
            {"name": "message", "type": "text", "label": "Message"},
        ],
        "result_fields": ["iv_hex", "c_hex", "recovered"],
        "tags": ["construction", "hardening"],
        "summary": "Runs CBC, OFB, or CTR over the AES foundation.",
        "claim": "Mode choice turns a fixed-block PRP/PRF into useful encryption.",
    },
    {
        "id": "pa5-mac",
        "pa": 5,
        "title": "Message Authentication Code",
        "category": "Minicrypt",
        "primitive": "MAC",
        "path": "/api/pa5/mac",
        "method": "POST",
        "default_payload": {"kind": "CBCMAC", "key": HEX16, "message": "auth me"},
        "controls": [
            {"name": "kind", "type": "select", "label": "MAC kind", "options": ["CBCMAC", "PRFMAC"]},
            {"name": "key", "type": "hex", "label": "Key"},
            {"name": "message", "type": "text", "label": "Message"},
        ],
        "result_fields": ["tag_hex", "verify"],
        "tags": ["construction", "hardening"],
        "summary": "Computes and verifies a tag for message integrity.",
        "claim": "EUF-CMA security reduces to PRF/PRP security in these constructions.",
    },
    {
        "id": "pa6-cca",
        "pa": 6,
        "title": "Encrypt-then-MAC CCA Encryption",
        "category": "Minicrypt",
        "primitive": "CCA-Enc",
        "path": "/api/pa6/cca",
        "method": "POST",
        "default_payload": {"k_E": "11" * 16, "k_M": "22" * 16, "message": "secret", "tamper": True},
        "controls": [
            {"name": "message", "type": "text", "label": "Message"},
            {"name": "tamper", "type": "boolean", "label": "Tamper ciphertext"},
        ],
        "result_fields": ["recovered", "rejected"],
        "tags": ["construction", "attack", "hardening"],
        "summary": "Shows ciphertext tampering rejected by Encrypt-then-MAC.",
        "claim": "CCA security follows from CPA encryption plus EUF-CMA authentication.",
    },
    {
        "id": "pa7-md",
        "pa": 7,
        "title": "Merkle-Damgard Hash",
        "category": "Hashing",
        "primitive": "CRHF",
        "path": "/api/pa7/md",
        "method": "POST",
        "default_payload": {"message": "hello", "block_size": 16, "output_size": 8},
        "controls": [
            {"name": "message", "type": "text", "label": "Message"},
            {"name": "block_size", "type": "number", "label": "Block size", "min": 16, "max": 64},
            {"name": "output_size", "type": "number", "label": "Output bytes", "min": 4, "max": 16},
        ],
        "result_fields": ["digest_hex"],
        "tags": ["construction"],
        "summary": "Builds an arbitrary-length hash from fixed compression.",
        "claim": "Collision resistance lifts from the compression function under MD strengthening.",
    },
    {
        "id": "pa8-hash",
        "pa": 8,
        "title": "DLP Collision-Resistant Hash",
        "category": "Hashing",
        "primitive": "CRHF",
        "path": "/api/pa8/hash",
        "method": "POST",
        "default_payload": {"message": "hello", "bits": 80},
        "controls": [
            {"name": "message", "type": "text", "label": "Message"},
            {"name": "bits", "type": "number", "label": "DLP bits", "min": 32, "max": 256},
        ],
        "result_fields": ["digest_hex"],
        "tags": ["construction"],
        "summary": "Hashes messages using the DLP-based construction.",
        "claim": "Finding collisions would reveal a discrete-log relation.",
    },
    {
        "id": "pa9-birthday",
        "pa": 9,
        "title": "Birthday Collision Attack",
        "category": "Attack",
        "primitive": "CRHF",
        "path": "/api/pa9/birthday",
        "method": "POST",
        "default_payload": {"n_bits": 8, "dlp_bits": 80},
        "controls": [
            {"name": "n_bits", "type": "number", "label": "Truncated bits", "min": 8, "max": 24},
        ],
        "result_fields": ["found", "queries", "expected_2_to_n_over_2"],
        "tags": ["attack"],
        "summary": "Finds a collision in a deliberately truncated hash output.",
        "claim": "Collision search appears around 2^(n/2), matching the birthday bound.",
    },
    {
        "id": "pa10-hmac",
        "pa": 10,
        "title": "HMAC",
        "category": "Hashing",
        "primitive": "HMAC",
        "path": "/api/pa10/hmac",
        "method": "POST",
        "default_payload": {"key": HEX16, "message": "hi"},
        "controls": [
            {"name": "key", "type": "hex", "label": "Key"},
            {"name": "message", "type": "text", "label": "Message"},
        ],
        "result_fields": ["tag_hex", "verify"],
        "tags": ["construction", "hardening"],
        "summary": "Computes a keyed hash tag with inner/outer pads.",
        "claim": "HMAC turns a hash into a MAC under standard assumptions.",
    },
    {
        "id": "pa11-dh",
        "pa": 11,
        "title": "Diffie-Hellman and MITM",
        "category": "Public Key",
        "primitive": "PKC",
        "path": "/api/pa11/dh",
        "method": "POST",
        "default_payload": {"bits": 128, "mitm": True},
        "controls": [
            {"name": "bits", "type": "number", "label": "Group bits", "min": 64, "max": 256},
            {"name": "mitm", "type": "boolean", "label": "Enable MITM"},
        ],
        "result_fields": ["K_alice", "K_bob", "K_eve_alice", "K_eve_bob"],
        "tags": ["construction", "attack"],
        "summary": "Compares honest key exchange with an active man-in-the-middle.",
        "claim": "Unauthenticated DH is vulnerable to active substitution.",
    },
    {
        "id": "pa12-rsa",
        "pa": 12,
        "title": "RSA and PKCS#1 Randomization",
        "category": "Public Key",
        "primitive": "PKC",
        "path": "/api/pa12/rsa",
        "method": "POST",
        "default_payload": {"bits": 512, "message": "hi", "mode": "pkcs"},
        "controls": [
            {"name": "mode", "type": "select", "label": "Mode", "options": ["textbook", "pkcs"]},
            {"name": "message", "type": "text", "label": "Message"},
        ],
        "result_fields": ["N", "e", "all_identical", "different", "recovered"],
        "tags": ["construction", "attack", "hardening"],
        "summary": "Contrasts deterministic textbook RSA with randomized PKCS#1-style encryption.",
        "claim": "Trapdoor permutations need padding/randomization for encryption security.",
    },
    {
        "id": "pa13-miller-rabin",
        "pa": 13,
        "title": "Miller-Rabin Primality",
        "category": "Number Theory",
        "primitive": "PKC",
        "path": "/api/pa13/miller_rabin",
        "method": "POST",
        "default_payload": {"n": 561, "rounds": 10},
        "controls": [
            {"name": "n", "type": "number", "label": "Candidate n", "min": 2},
            {"name": "rounds", "type": "number", "label": "Rounds", "min": 1, "max": 40},
        ],
        "result_fields": ["miller_rabin", "fermat", "is_carmichael_561_demo"],
        "tags": ["construction", "attack"],
        "summary": "Uses Carmichael 561 to show why Fermat alone is insufficient.",
        "claim": "Miller-Rabin catches composites that fool simpler Fermat testing.",
    },
    {
        "id": "pa14-hastad",
        "pa": 14,
        "title": "Hastad Broadcast Attack",
        "category": "Attack",
        "primitive": "PKC",
        "path": "/api/pa14/hastad",
        "method": "POST",
        "default_payload": {"m": 4660},
        "controls": [
            {"name": "m", "type": "number", "label": "Plaintext integer", "min": 1},
        ],
        "result_fields": ["recovered_m", "match_original", "is_perfect_root"],
        "tags": ["attack"],
        "summary": "Recovers the same low-exponent RSA message sent to multiple recipients.",
        "claim": "Textbook RSA with e=3 and no padding is broadcast-attack vulnerable.",
    },
    {
        "id": "pa15-sign",
        "pa": 15,
        "title": "Digital Signature Verification",
        "category": "Public Key",
        "primitive": "DigitalSig",
        "path": "/api/pa15/sign",
        "method": "POST",
        "default_payload": {"message": "I agree", "tamper": True},
        "controls": [
            {"name": "message", "type": "text", "label": "Message"},
            {"name": "tamper", "type": "boolean", "label": "Tamper message"},
        ],
        "result_fields": ["sigma", "verify", "tamper"],
        "tags": ["construction", "attack", "hardening"],
        "summary": "Signs a message and shows verification failing after tampering.",
        "claim": "Hash-then-sign binds signatures to exact message contents.",
    },
    {
        "id": "pa16-elgamal",
        "pa": 16,
        "title": "ElGamal Malleability",
        "category": "Attack",
        "primitive": "PKC",
        "path": "/api/pa16/elgamal",
        "method": "POST",
        "default_payload": {"m": 42, "multiplier": 3},
        "controls": [
            {"name": "m", "type": "number", "label": "Plaintext integer", "min": 1},
            {"name": "multiplier", "type": "number", "label": "Attack multiplier", "min": 2},
        ],
        "result_fields": ["recovered", "malleability"],
        "tags": ["attack"],
        "summary": "Modifies a ciphertext so decryption scales the plaintext.",
        "claim": "Plain ElGamal is multiplicatively malleable without authentication.",
    },
    {
        "id": "pa17-signcrypt",
        "pa": 17,
        "title": "Signcryption Tamper Rejection",
        "category": "Public Key",
        "primitive": "CCA-PKC",
        "path": "/api/pa17/signcrypt",
        "method": "POST",
        "default_payload": {"m": 12345, "tamper": True},
        "controls": [
            {"name": "m", "type": "number", "label": "Plaintext integer", "min": 1},
            {"name": "tamper", "type": "boolean", "label": "Tamper ciphertext"},
        ],
        "result_fields": ["recovered", "rejected"],
        "tags": ["construction", "attack", "hardening"],
        "summary": "Combines encryption and signatures to reject tampered public-key ciphertexts.",
        "claim": "CCA-secure public-key encryption needs integrity/authentication.",
    },
    {
        "id": "pa18-ot",
        "pa": 18,
        "title": "Oblivious Transfer",
        "category": "MPC",
        "primitive": "OT",
        "path": "/api/pa18/ot",
        "method": "POST",
        "default_payload": {"b": 1, "m0": 11, "m1": 22},
        "controls": [
            {"name": "b", "type": "select", "label": "Choice bit", "options": [0, 1]},
            {"name": "m0", "type": "number", "label": "m0"},
            {"name": "m1", "type": "number", "label": "m1"},
        ],
        "result_fields": ["received", "expected"],
        "tags": ["construction", "mpc"],
        "summary": "Receiver obtains one selected message without learning both.",
        "claim": "OT is the bridge from public-key assumptions to secure computation.",
    },
    {
        "id": "pa19-and",
        "pa": 19,
        "title": "Secure AND Gate",
        "category": "MPC",
        "primitive": "SecureAND",
        "path": "/api/pa19/and",
        "method": "POST",
        "default_payload": {"a": 1, "b": 1},
        "controls": [
            {"name": "a", "type": "select", "label": "Input a", "options": [0, 1]},
            {"name": "b", "type": "select", "label": "Input b", "options": [0, 1]},
        ],
        "result_fields": ["a", "b", "result", "expected"],
        "tags": ["construction", "mpc"],
        "summary": "Computes an AND gate through OT-backed secure evaluation.",
        "claim": "Secure AND plus local XOR/NOT is enough for Boolean circuits.",
    },
    {
        "id": "pa20-mpc",
        "pa": 20,
        "title": "Two-Party MPC Circuit",
        "category": "MPC",
        "primitive": "MPC",
        "path": "/api/pa20/mpc",
        "method": "POST",
        "default_payload": {"circuit": "millionaires", "n": 4, "x": 7, "y": 12},
        "controls": [
            {"name": "circuit", "type": "select", "label": "Circuit", "options": ["millionaires", "equality", "bit_add"]},
            {"name": "n", "type": "number", "label": "Bit width", "min": 2, "max": 8},
            {"name": "x", "type": "number", "label": "Alice x", "min": 0},
            {"name": "y", "type": "number", "label": "Bob y", "min": 0},
        ],
        "result_fields": ["circuit", "result", "and_gates", "total_gates"],
        "tags": ["construction", "mpc"],
        "summary": "Runs equality, addition, or millionaire comparison as secure circuits.",
        "claim": "OT-backed gates scale to full two-party circuit evaluation.",
    },
]


def get_demo_catalog():
    """Return a JSON-serializable copy of the demo catalog."""
    return [dict(item) for item in DEMO_CATALOG]
